name: lint

on:
  push:
    paths:
      - '.github/workflows/*'

jobs:
  lint-workflow-files:
    name: lint workflow files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://rhysd/actionlint:latest
