name: lint

on:
  push:
    paths:
      - '.github/workflows/*'

jobs:
  lint-workflow-files:
    name: lint workflow files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: docker://rhysd/actionlint:latest
