name: test

on:
  - push
  - pull_request

jobs:
  test:
    name: test
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
